file(GLOB PROJECTUNITY_GAME_SCRIPT_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/Assets/Scripts/*.cpp"
)

add_library(ProjectUnityGameScripts SHARED
    ${PROJECTUNITY_GAME_SCRIPT_SOURCES}
)

add_library(ProjectUnity::GameScripts ALIAS ProjectUnityGameScripts)

target_link_libraries(ProjectUnityGameScripts
    PRIVATE
        ProjectUnity::Scripting
)

projectunity_configure_target(ProjectUnityGameScripts)

set(PROJECTUNITY_GAME_SCRIPTS_OUTPUT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Binaries/Scripts")

set_target_properties(ProjectUnityGameScripts PROPERTIES
    OUTPUT_NAME "ProjectUnityGameScripts"
    RUNTIME_OUTPUT_DIRECTORY "${PROJECTUNITY_GAME_SCRIPTS_OUTPUT_DIR}"
    LIBRARY_OUTPUT_DIRECTORY "${PROJECTUNITY_GAME_SCRIPTS_OUTPUT_DIR}"
    ARCHIVE_OUTPUT_DIRECTORY "${PROJECTUNITY_GAME_SCRIPTS_OUTPUT_DIR}"
)

foreach(PROJECTUNITY_CONFIG Debug Release RelWithDebInfo MinSizeRel)
    string(TOUPPER "${PROJECTUNITY_CONFIG}" PROJECTUNITY_CONFIG_UPPER)
    set_target_properties(ProjectUnityGameScripts PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY_${PROJECTUNITY_CONFIG_UPPER} "${PROJECTUNITY_GAME_SCRIPTS_OUTPUT_DIR}"
        LIBRARY_OUTPUT_DIRECTORY_${PROJECTUNITY_CONFIG_UPPER} "${PROJECTUNITY_GAME_SCRIPTS_OUTPUT_DIR}"
        ARCHIVE_OUTPUT_DIRECTORY_${PROJECTUNITY_CONFIG_UPPER} "${PROJECTUNITY_GAME_SCRIPTS_OUTPUT_DIR}"
    )
endforeach()
