if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED SYMBOL_NAME)
    message(FATAL_ERROR "INPUT_FILE, OUTPUT_FILE and SYMBOL_NAME are required")
endif()

file(READ "${INPUT_FILE}" SPIRV_HEX HEX)
string(LENGTH "${SPIRV_HEX}" SPIRV_HEX_LENGTH)
math(EXPR SPIRV_BYTE_LENGTH "${SPIRV_HEX_LENGTH} / 2")
math(EXPR SPIRV_WORD_COUNT "${SPIRV_BYTE_LENGTH} / 4")

set(SPIRV_WORDS "")
foreach(WORD_INDEX RANGE 0 ${SPIRV_WORD_COUNT})
    math(EXPR BYTE_OFFSET "${WORD_INDEX} * 8")
    if(BYTE_OFFSET GREATER_EQUAL SPIRV_HEX_LENGTH)
        break()
    endif()
    string(SUBSTRING "${SPIRV_HEX}" ${BYTE_OFFSET} 2 BYTE0)
    math(EXPR BYTE1_OFFSET "${BYTE_OFFSET} + 2")
    math(EXPR BYTE2_OFFSET "${BYTE_OFFSET} + 4")
    math(EXPR BYTE3_OFFSET "${BYTE_OFFSET} + 6")
    string(SUBSTRING "${SPIRV_HEX}" ${BYTE1_OFFSET} 2 BYTE1)
    string(SUBSTRING "${SPIRV_HEX}" ${BYTE2_OFFSET} 2 BYTE2)
    string(SUBSTRING "${SPIRV_HEX}" ${BYTE3_OFFSET} 2 BYTE3)
    string(APPEND SPIRV_WORDS "    0x${BYTE3}${BYTE2}${BYTE1}${BYTE0}U,\n")
endforeach()

get_filename_component(OUTPUT_DIRECTORY "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_FILE}" "#pragma once\n\n")
file(APPEND "${OUTPUT_FILE}" "#include <array>\n")
file(APPEND "${OUTPUT_FILE}" "#include <cstdint>\n\n")
file(APPEND "${OUTPUT_FILE}" "namespace projectunity::renderer::shaders {\n")
file(APPEND "${OUTPUT_FILE}" "inline constexpr std::array<std::uint32_t, ${SPIRV_WORD_COUNT}> ${SYMBOL_NAME} {{\n")
file(APPEND "${OUTPUT_FILE}" "${SPIRV_WORDS}")
file(APPEND "${OUTPUT_FILE}" "}};\n")
file(APPEND "${OUTPUT_FILE}" "} // namespace projectunity::renderer::shaders\n")
